"""empty message

Revision ID: 18054bb99636
Revises: ccaaca3fc327
Create Date: 2020-02-14 00:46:46.384682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18054bb99636'
down_revision = 'ccaaca3fc327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuler', sa.Column('menuid', sa.String(length=255), nullable=True))
    op.add_column('slayt', sa.Column('slaytid', sa.String(length=50), nullable=True))
    op.add_column('yemekler1', sa.Column('yemekid1', sa.String(length=50), nullable=True))
    op.add_column('yemekler2', sa.Column('yemekid2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yemekler2', 'yemekid2')
    op.drop_column('yemekler1', 'yemekid1')
    op.drop_column('slayt', 'slaytid')
    op.drop_column('menuler', 'menuid')
    # ### end Alembic commands ###
