"""empty message

Revision ID: 6f83fc9f11a1
Revises: b7bcc18fc765
Create Date: 2020-02-13 21:22:38.112687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f83fc9f11a1'
down_revision = 'b7bcc18fc765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yemekler1', sa.Column('yemekisim', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yemekler1', 'yemekisim')
    # ### end Alembic commands ###
