"""empty message

Revision ID: ded23c14eaf0
Revises: 18054bb99636
Create Date: 2020-02-14 04:41:31.828405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded23c14eaf0'
down_revision = '18054bb99636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullaniciadi', sa.String(length=50), nullable=True),
    sa.Column('sifre', sa.String(length=50), nullable=True),
    sa.Column('resim', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici')
    # ### end Alembic commands ###
